command_timeout = 2000

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 10
truncate_to_repo = false
truncation_symbol = ".../"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = '${count}⇣'

[username]
show_always = true
